# Welcome {.unnumbered}

Welcome everyone to the workshop, "Is Machine Learning Suitable for Your Projects?" 

- **When** 🕘
    9 am to 3:30 pm on August 24th, 2024

- **Where?** 📍
    [P.A. Woodward Instructional Resources Centre (IRC) - 4](https://learningspaces.ubc.ca/classrooms/irc-4), 2194 Health Sciences Mall, Vancouver BC, V6T 1Z3

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2603.6128489255175!2d-123.24931208692584!3d49.26478357190086!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548672c9cd9276dd%3A0xe4b701c0a7916421!2s2194%20Health%20Sciences%20Mall%2C%20Vancouver%2C%20BC%20V6T%202A1!5e0!3m2!1sen!2sca!4v1724336924533!5m2!1sen!2sca" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

This workshop is a collaboration between [the Data Science Institute](https://dsi.ubc.ca/), [the Master of Data Science, Vancouver program](https://masterdatascience.ubc.ca/programs/vancouver) and [the Department of Computer Science](https://www.cs.ubc.ca/) at UBC. 

The Data Science Institute (DSI) is dedicated to fostering and advancing research, innovation, and training in data-intensive sciences. While we collaborate with researchers and external partners to achieve these objectives, we also prioritize providing valuable learning experiences for undergraduate and graduate students from diverse backgrounds. This workshop is part of our broader effort to introduce data science concepts to students and researchers, especially to those from non-STEM fields. We hope that this initiative will inspire participants to further explore the field of data science and its applications.

The Computer Science Department is pleased to offer this workshop to their mentors as a token of appreciation and a valuable opportunity for professional development.

In this workshop, you will discover how machine learning can improve your research projects. The workshop is tailored for non-STEM students and researchers. We will demystify the fundamentals of machine learning and clarify what it can and cannot do for your research. By the end of the workshop, you will be familiar with the fundamentals of machine learning and different types of machine learning. 
