# Welcome {.unnumbered}

Welcome everyone to the "CS Alumni Workshop: Is Machine Learning Suitable for Your Projects?" 

- **When** 🕘
    9:30 am to 4:00 pm on December 7th, 2024

- **Where?** 📍
    [Room 4074 of the UBC Orchard Commons](https://learningspaces.ubc.ca/classrooms/orch-4074), 6363 Agronomy Rd, Vancouver, BC V6T 1Z4


<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2603.853164736889!2d-123.2535824882542!3d49.26022897127008!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548672cba66be131%3A0x4e5c75d2f5097ca5!2s6363%20Agronomy%20Rd%2C%20Vancouver%2C%20BC%20V6T%201Z4!5e0!3m2!1sen!2sca!4v1732719337824!5m2!1sen!2sca" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

This workshop is a collaboration between [the Master of Data Science, Vancouver program](https://masterdatascience.ubc.ca/programs/vancouver) and [the Department of Computer Science](https://www.cs.ubc.ca/) at UBC. 

The Computer Science Department is pleased to offer this workshop to their alumni as a token of appreciation and a valuable opportunity for professional development.

In this workshop, you will discover how machine learning can improve your research projects. The workshop is tailored for students and researchers with some programming background. We will demystify the fundamentals of machine learning and clarify what it can and cannot do for your work and/or research. By the end of the workshop, you will be familiar with the fundamentals of machine learning and different types of machine learning. 
